# docker build -t rabbit:3.9.13 .
# docker run -d --rm --name rabbit -e RABBITMQ_DEFAULT_USER=db -e RABBITMQ_DEFAULT_PASS=db -p 10000:5671 -p 10001:15671 rabbit:3.9.13

FROM rabbitmq:3.9.13-management

COPY $PWD/certificates/ca.pem /etc/ssl/certs/rabbit/
COPY $PWD/certificates/server-cert.pem /etc/ssl/certs/rabbit/
COPY $PWD/certificates/server-key.pem /etc/ssl/certs/rabbit/
RUN chown -R rabbitmq:rabbitmq /etc/ssl/certs/rabbit/*
RUN chmod 600 /etc/ssl/certs/rabbit/*

COPY $PWD/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
